// Auto-generated aggregator from themes
import * as Themes from './themes';

export const MUSIC_THEME_LIST = [
  Themes.THEME_SOUNDTRACK_1,
  Themes.THEME_SOUNDTRACK_2,
  Themes.THEME_SOUNDTRACK_3,
  Themes.THEME_SOUNDTRACK_4,
  Themes.MOVIES_1,
  Themes.MOVIES_2,
  Themes.METAL_1,
  Themes.METAL_2,
  Themes.METAL_HARD,
  Themes.ROCK,
  Themes.POPROCK,
  Themes.ROCK_3,
  Themes.EUROVISION,
  Themes.POP_1,
  Themes.TOP_SPOTIFY_2000,
  Themes.SPOTIFY_FROM_2010,
  Themes.POP_NEW,
  Themes.DANCE,
  Themes.RAP,
  Themes.RAP2,
  Themes.TEST,
  Themes.THEME_BELARUS,
  Themes.THEME_BELARUS_2,
  Themes.THEME_UKRAINE,
  Themes.OLDOLD,
  Themes.THEME_80S,
  Themes.THEME_80S_2,
  Themes.X90,
  Themes.X902,
  Themes.THEME_90S,
  Themes.THEME_00S,
  Themes.X2000_2010_2,
  Themes.X2000_2010_3,
  Themes.THEME_ACTUAL,
  Themes.LANG,
  Themes.GUES_LANGUAGE,
  Themes.RANDOM,
  Themes.MOVIES_PHOTOS,
  Themes.STARS_PHOTOS,
  Themes.MULTFILM,
  Themes.ADD,
  Themes.THEME_MOVIES_2025,
];
